# -*- coding: utf-8 -*-
"""Typing test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/awchisholm/typingtest/blob/master/Typing_test.ipynb
"""

#@title Download a book
# This downloads a book
import requests
example_txt = 'https://gutenberg.org/files/1661/1661-0.txt'
book = requests.get(example_txt)
with open('/content/book.txt', 'wb') as f:
    f.write(book.content)

#@title Select 5 words somewhere in the text
# This chooses 5 words somewhere in the text
import random
booktext = book.text
better_words = booktext.split()
allWords = len(better_words)
lengthOfSentence = 5
startOfSentence = random.randint(1, allWords - lengthOfSentence)
sentence = better_words[startOfSentence:startOfSentence+lengthOfSentence]

StringToType = ' '.join(sentence)

#@title Get the user to type these 5 words
# This asks the user to type the 5 words
# and times it.
# The editdistance is how many errors were made
# 0 errors is good
from time import time
import editdistance

TypeThis = 'Type this -->'
stime = time()
FromUser = input(f'{TypeThis} {StringToType} ')
etime = time()
ElapsedTime = round(etime - stime, 2)
edistance = editdistance.eval(FromUser, StringToType)

print(f'You made {edistance} errors in {ElapsedTime} seconds')