# -*- coding: utf-8 -*-
"""ImprovedComplexTypingTest

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W8lSmkSnITZbrp360mn5PQn8BY_oTjAc
"""

booktext = """ At three o’clock precisely I was at Baker Street, but Holmes had not
yet returned. The landlady informed me that he had left the house
shortly after eight o’clock in the morning. I sat down beside the fire,
however, with the intention of awaiting him, however long he might be.
I was already deeply interested in his inquiry, for, though it was
surrounded by none of the grim and strange features which were
associated with the two crimes which I have already recorded, still,
the nature of the case and the exalted station of his client gave it a
character of its own. Indeed, apart from the nature of the
investigation which my friend had on hand, there was something in his
masterly grasp of a situation, and his keen, incisive reasoning, which
made it a pleasure to me to study his system of work, and to follow the
quick, subtle methods by which he disentangled the most inextricable
mysteries. So accustomed was I to his invariable success that the very
possibility of his failing had ceased to enter into my head."""

#@title Select 5 words somewhere in the text
# This chooses 5 words somewhere in the text
import random
better_words = booktext.split()
allWords = len(better_words)
lengthOfSentence = 5
startOfSentence = random.randint(1, allWords - lengthOfSentence)
sentence = better_words[startOfSentence:startOfSentence+lengthOfSentence]

StringToType = ' '.join(sentence)

#@title Get the user to type these 5 words
# This asks the user to type the 5 words
# and times it.
# The editdistance is how many errors were made
# 0 errors is good
from time import time
import editdistance

TypeThis = 'Type this -->'
stime = time()
FromUser = input(f'{TypeThis} {StringToType} ')
etime = time()
ElapsedTime = round(etime - stime, 2)
edistance = editdistance.eval(FromUser, StringToType)

print(f'You made {edistance} errors in {ElapsedTime} seconds')
