# -*- coding: utf-8 -*-
"""RockPaperScissorsWithData

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/awchisholm/typingtest/blob/master/RockPaperScissorsWithData.ipynb
"""

from collections import defaultdict
import random
choices = ('Rock', 'Paper', 'Scissors', 'Quit ')
computer_wins = 'Computer wins'
player_wins = 'Player wins'
draw = 'Draw'
d2_dict = defaultdict(dict)
d2_dict[('Player', 'Computer')] = 'Winner'
d2_dict[('Rock', 'Paper')] = computer_wins
d2_dict[('Rock', 'Scissors')] = player_wins 
d2_dict[('Rock', 'Rock')] = draw 
d2_dict[('Paper', 'Scissors')] = computer_wins
d2_dict[('Paper', 'Rock')] = player_wins 
d2_dict[('Paper', 'Paper')] = draw 
d2_dict[('Scissors', 'Scissors')] = draw 
d2_dict[('Scissors', 'Rock')] = computer_wins 
d2_dict[('Scissors', 'Paper')] = player_wins

player_name = input("enter name ")
computer_name = 'Computer'
computer_score = 0
player_score = 0
while True:
  choice = input(choices)
  if 'Quit' in choice:
    break
  if choice not in choices:
    continue
  computer = choices[random.randint(0,2)]
  result = d2_dict[(choice, computer)]
  if result == computer_wins:
    computer_score += 1
  if result == player_wins:
    player_score += 1
  print(f"{player_name}:{choice} vs {computer_name}:{computer}. Result:{result}")
  print(f"Running totals... player:{player_score} computer:{computer_score}")
